config/routes.rb
Rails.application.routes.draw do

  # CUSTOM ROUTES ON TOP
  
root 'welcome#home'

get '/login' => "sessions#new"
post '/sessions' => "sessions#create"
get '/logout' => "sessions#destroy"

#get '/auth/:provider/callback' => 'sessions#create'
get '/auth/github/callback' => 'sessions#create'
get '/auth/google/callback' => 'sessions#create'
        # provider is also called 'STRATEGY'

get '/signup' => 'users#new'
        
  resources :users, only: [:new, :create, :show] do
    #nested routes
    resources :events, only: [:index, :show, :new, :create]
    get 'search', to: "events#search"
  end


resources :events
#resources :categories, except: [:destroy]
# post '/users_events', to: 'users_events#create', as: 'new_usersevent'

resources :users_events, only: [:create, :destroy]
get 'rsvps', to: "users_events#index"

get 'search', to: "events#search"
get 'state-search', to: "events#search_by_state", as: "state_search"

get 'users', to: "users#users"

end

app/models/user.rb
class User < ApplicationRecord
    has_many :users_events, dependent: :destroy
    has_many :events, through: :users_events
            # @user.events

    has_secure_password
    validates_presence_of :username, :email, :password
    validates :username, uniqueness: true
    validates :email, uniqueness: true


    def self.find_or_create_by_omniauth(auth_hash)
        #raise.params
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
            user.username = auth_hash["info"][:nickname]
        end
    end

    def events_where_admin
        #byebug
        #self.users_events.where(admin: true)
        self.users_events.where(admin: true).pluck(:event_id).collect { |ei| ei.event }
        
        # user_events table and we are finding any row where user_id = is equal to this user.id(self)
        # and admin = true
        # taking all the event_id's out of those rows on the user_events table, iterate over those id's [bracket/array of id's]
        # creating an array of event instances from those id's
    end



end


# @user.users_events.where(admin: true)

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authentication_required, only: [:show, :edit, :destroy]
                # is this a ^callback^ ?
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        #byebug
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def users 
        redirect_to '/'
    end

    def show
        if current_user == nil
            redirect_to login_path
            flash[:message] = "You must be logged in to access your dashboard"
        else
            @user = User.find_by(id: params[:id])
            authorize(@user)
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end
    
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<br>
<div>

<% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
        <p style="color:#FF0000";><%= message %></p>
    <% end %>
    </ul>
<% end %>

    <%= form_for @user do |f| %>

        <%= f.text_field :name, "size" => 30, :placeholder => :name %><br>
    <br>
        <%= f.text_field :username, "size" => 30, :placeholder => :username %><br>

    <br>
        <%= f.email_field :email, "size" => 30, :placeholder => :email %><br>

    <br>
        <%= f.password_field :password, "size" => 30, :placeholder => :password %>
    <br></br>
        <%= submit_tag("Create User", :style => "width: 100px; background-color: #c49102;") %>
    <% end %>

</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upcoming Events</title>
    <link rel="stylesheet" href="#">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <div>
    <br>
        <h1 class="animate__animated animate__fadeIn">Sign Up</h1>
        <p>Already on board? <%= link_to "Log In", '/login' %></p>

        <%= render 'form' %>

    </div>
</body>

app/views/users/show.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Dashboard</title>
    <link rel="stylesheet" href="users.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <br></br>
    <div>
        <div>
            <h1 class="animate__animated animate__backInUp" style="color:#FFFFFF"; > Hello <%= @user.name || @user.username.capitalize %> </h1> 
            <%#= link_to "See All Events", events_path %>
            <%= link_to "Create New Event", new_user_event_path(@user) %>
        <div>

    <br>
        <div>
            <%# raise.params %> <%# %>
            <h5>Click <%= link_to "Here", user_events_path(@user) %> To See ALL The Events You're Going To!</h5>
                                    <%# byebug %>
                                        <%# @user.events.each do |event| %>
                                            <%# byebug %>
                                            <%#= link_to event.title, event_path(event) %> -
                                            <%# ed = event.date %>
                                            <%#= ed.strftime("%m/%d/%Y") %> -
                                            <%# et = event.time %>
                                            <%#= et.strftime("%I:%M %p") %>
                                            <br>
                                        <%# end %> <%# %>
        </div>

        <div>
            <br>
            <h5><u>Events You Have Created</u></h5>
            <%# byebug %><%# %>
                <% if @user.users_events.where(admin: true).empty? %>
                    <p style="color: #ffffff;"><%= "You haven't created any events yet!" %><p>
                <% else @user.users_events.where(admin: true) %>
                                            <%# @user.users_events.where(admin: true){order("date")}.each do |event| %> <%# %>
                    <% @user.users_events.where(admin: true).reverse.each do |uevent| %>
                        <%# byebug %>
                        <% if @user %>
                            <%= link_to uevent.event.title, user_event_path(@user, uevent.event) %> -
                        <% else %>
                            <%= link_to uevent.event.title, event_path(event.event_id) %> -
                        <% end %>
                        <% ed = uevent.event.date %>
                        <%= ed.strftime("%m/%d/%Y") %>
                        <br>        
                    <% end %>
                <% end %>
        </div>

    </div>
</body>