config/routes.rb
Rails.application.routes.draw do

  # CUSTOM ROUTES ON TOP
  
root 'welcome#home'

get '/login' => "sessions#new"
post '/sessions' => "sessions#create"
get '/logout' => "sessions#destroy"

#get '/auth/:provider/callback' => 'sessions#create'
get '/auth/github/callback' => 'sessions#create'
get '/auth/google/callback' => 'sessions#create'
        # provider is also called 'STRATEGY'

get '/signup' => 'users#new'
        
  resources :users, only: [:new, :create, :show] do
    #nested routes
    resources :events, only: [:index, :show, :new, :create]
    get 'search', to: "events#search"
  end


resources :events
#resources :categories, except: [:destroy]
# post '/users_events', to: 'users_events#create', as: 'new_usersevent'

resources :users_events, only: [:create, :destroy]
get 'rsvps', to: "users_events#index"

get 'search', to: "events#search"
get 'state-search', to: "events#search_by_state", as: "state_search"

get 'users', to: "users#users"

end

app/models/event.rb
class Event < ApplicationRecord

    include ActiveModel::Validations

    has_many :users_events, dependent: :destroy
    has_many :users, through: :users_events
                # @event.users

    validates_presence_of :title, :category, :address, :city, :state, :zip, :time, :about_content
    validates :zip, length: { is: 5 }
    validates_numericality_of :zip
                # validate :date_must_be_after_today
    validates_with DateValidator, on: :create
    
    scope :future_date, lambda { where("date > ?", Date.today) }
                # ARel query?
                # scope allows you to specify an ARel query that can be used as a method call to the model (or association objects)
                # equivalent to: 
    scope :order_by_date, -> {order("date")}

    # scope :users_state, -> { where("state" == )}
    
                # def date_must_be_after_today       #(((this method went into DateValidator)))
                #     if date <= Time.now
                #         errors.add(:date, "must be after today")
                #     end
                # end

    def is_admin?(user)
        self.users_events.where(admin: true).pluck(:user_id).include?(user.id)
    end 

    def self.search(params)
        # @events = Event.order_by_date.where("(title || about_content || category) LIKE ?", "%" + params[:search] + "%")
        # ^case sensitive in PG^ or (below) can only search one attr/field
        # @events = Event.order_by_date.where(Event.arel_table[:title].matches("%#{params[:search]}%")) #https://www.scimedsolutions.com/blog/arel-part-i-case-insensitive-searches-with-partial-matching
      
        @events = Event.order_by_date.where(
            %i(title category about_content state)
            .map { |field| Event.arel_table[field].matches("%#{params[:search]}%")}
            .inject(:or)
        )     #https://www.thetopsites.net/article/53226084.shtml
       
    end
        
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
            # is this a ^callback^ ?
    
    def index
        #byebug
        if params[:user_id]
            # @user = User.find_by(params[:id]) found this on StackOverflow - Doesn't work - only pulls first instance of user
            # ^^ @category = Category.find(params[:id]) / @posts = @category.posts ^^
            @user = User.find_by(:id => current_user)
            #byebug
            @events = @user.events.order_by_date.future_date
        else
            @events = Event.order_by_date.future_date
        end
    end

    def search
        @events = Event.search(params)
    end

    

    def search_by_state
        # @events = Event.order_by_date.where("(state) LIKE ?", "%" + params[:search].upcase + "%")
        # render 'search'

        @events = Event.order_by_date.where(
            %i(state)
            .map { |field| Event.arel_table[field].matches("%#{params[:search]}%")}
        .inject(:or)
        )
        render 'search'
    end

    def new
        if current_user == nil
            redirect_to login_path
            flash[:message] = "You must be logged in to create an event"
        end
        @event = Event.new
    end
    
    def create
        @event = Event.new(event_params)
        if @event.save
            #byebug
            @userevent = @event.users_events.build(user_id: current_user.id, admin: true)
            # @userevent.comment = "Of Course I'm going, I made the event!"
            @userevent.comment = "I'm this events' organizer!"
            @userevent.save
            #byebug
            redirect_to event_path(@event)
        else
            render :new
        end
    end

    def show
        #byebug
        if current_user == nil
            redirect_to login_path
            flash[:message] = "You must be logged in to see events"
        end
        if @event == nil
            nested_event
        end

    end


    def edit
        @event = Event.find_by(id: params[:id])
        if @event.is_admin?(current_user)
            render :edit
        else 
            redirect_to events_path
            flash[:message] = "You must be Admin of Event to Edit"
        end 
    end
    
    def update
         # if @user.admin
        if @event.is_admin?(current_user)
            if @event.update(event_params)
                redirect_to event_path(@event)
            else
                render :edit
            end
        else
            redirect_to events_path
            flash[:message] = "You must be Admin of Event to Edit"
        end 
    end

    def destroy
        # if @user.admin 
        if @event.is_admin?(current_user)
            if @event.destroy
                redirect_to events_path
            else
                render :index
            end
        else
            redirect_to events_path
            flash[:message] = "You must be Admin of Event to Edit"
        end 
    end

    private

    def event_params
        params.require(:event).permit(:title, :category, :address, :city, :state, :zip, :date, :time, :about_content, users_event_attributes:[:comment, :user_id, :event_id])
    end

    def set_event
        #byebug
        @event = Event.find_by(id: params[:id])
    end

    def nested_event
        ue = UsersEvent.find_by(id: params[:id]).event_id
        @event = Event.find_by(id: ue)
    end
    
end

app/helpers/events_helper.rb
module EventsHelper

    def sj_categories
        [
            ['Celebrate Diversity', 'Celebrate Diversity'],
            ['LGBTQ Rights', 'LGBTQ Rights'],
            ['Pride', 'Pride'],
            ['Black Lives Matter', 'Black Lives Matter'],
            ['Equality', 'Equality'],
            ['Civil Rights', 'Civil Rights'],
            ['Human Rights', 'Human Rights'],
            ['Citizenship', 'Citizenship'],
            ['Refugee Rights', 'Refugee Rights'],
            ['DACA', 'DACA'],
            ['Migrant Worker Rights', 'Migrant Worker Rights'],
            ['Labor Exploitation', 'Labor Exploitation'],
            ['Injustice At The Border', 'Injustice At The Border'],
            ['Families Belong Together', 'Families Belong Together'],
            ['Climate Change', 'Climate Change'],
            ['VOTE!', 'VOTE!'],
            ['Voting Rights', 'Voting Rights'],
            ['Womens Rights', 'Womens Rights'],
            ['Abortion Rights', 'Abortion Rights'],
            ['Me Too', 'Me Too'],
            ['Healthcare', 'Healthcare'],
            ['Ageism', 'Ageism'],
            ['Gender', 'Gender'],
            ['Gun Violence', 'Gun Violence'],
            ['Child Welfare', 'Child Welfare'],
            ['Education', 'Education'],
            ['Teacher Salaries', 'Teacher Salaries'],
            ['Abuse', 'Abuse'],
            ['Domestic Violence', 'Domestic Violence'],
            ['Economic Reform', 'Economic Reform'],
            ['Poverty & Economic Justice', 'Poverty & Economic Justice'],
            ['Power To The People', 'Power To The People'],
            ['Prison Reform', 'Prison Reform'],
            ['Systemic Oppression', 'Systemic Oppression'],
            ['Mental Health', 'Mental Health'],
            ['March For Science', 'March For Science'],
            ['Impeach The President', 'Impeach The President']
        ]
    end

    def us_states
        [
            ['CO', 'CO'],
            ['AK', 'AK'],
            ['AL', 'AL'],
            ['AR', 'AR'],
            ['AZ', 'AZ'],
            ['CA', 'CA'],
            ['CO', 'CO'],
            ['CT', 'CT'],
            ['DC', 'DC'],
            ['DE', 'DE'],
            ['FL', 'FL'],
            ['GA', 'GA'],
            ['HI', 'HI'],
            ['IA', 'IA'],
            ['ID', 'ID'],
            ['IL', 'IL'],
            ['IN', 'IN'],
            ['KS', 'KS'],
            ['KY', 'KY'],
            ['LA', 'LA'],
            ['MA', 'MA'],
            ['MD', 'MD'],
            ['ME', 'ME'],
            ['MI', 'MI'],
            ['MN', 'MN'],
            ['MO', 'MO'],
            ['MS', 'MS'],
            ['MT', 'MT'],
            ['NC', 'NC'],
            ['ND', 'ND'],
            ['NE', 'NE'],
            ['NH', 'NH'],
            ['NJ', 'NJ'],
            ['NM', 'NM'],
            ['NV', 'NV'],
            ['NY', 'NY'],
            ['OH', 'OH'],
            ['OK', 'OK'],
            ['OR', 'OR'],
            ['PA', 'PA'],
            ['RI', 'RI'],
            ['SC', 'SC'],
            ['SD', 'SD'],
            ['TN', 'TN'],
            ['TX', 'TX'],
            ['UT', 'UT'],
            ['VA', 'VA'],
            ['VT', 'VT'],
            ['WA', 'WA'],
            ['WI', 'WI'],
            ['WV', 'WV'],
            ['WY', 'WY']
        ]
    end

end

app/views/events/_form.html.erb
<br>
<div>


    <div>
        <% if @event.errors.any? %>
            <ul>
            <% @event.errors.full_messages.each do |message| %>
                <p style="color:#FF0000";><%= message %></p>
            <% end %>
            </ul>
        <% end %>
    </div>
    <div>
        <%= form_for @event do |f| %>
            
            <%= f.label "Title:" %><br>
            <%= f.text_field :title , "size" => 30 %>
            <br></br>
            <%= f.label "Category:" %><br>
            <%= f.select :category, options_for_select( sj_categories, " "), include_blank: "Select One" %>
            <br></br>
            <%= f.label "Address:" %><br>
            <%= f.text_field :address , "size" => 30 %>
            <br>
            <%= f.label :city%>
            <%= f.text_field :city %>
            <%= f.label :state%>
            <%= f.select :state, options_for_select(us_states, " ") %>
            <%= f.label :zip %>
            <%= f.text_field :zip, "size" => 5 %>
            <br></br>

            <%= f.label :date %>
            <%= f.date_field :date %>
            <%= f.label :time %>
            <%= f.time_field :time %>
            <br></br>

            <%= f.label "Event Info:" %><br>
            <%= f.text_area :about_content, cols: "50", rows: "10" %>
            <br></br>

            <%= f.submit(:style => "width: 150px; background-color: #c49102;") %>

        <% end %>
    </div>
</div>

app/views/events/_searchform.html.erb
<div>
    <%= form_tag ('/search'), :method => "get" do %>
        <%= label_tag(:search, "Looking for a specific event?") %><br>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag("Search", :name => nil) %>
    <% end %>
</div>

app/views/events/_statesearch.html.erb
<div>
    <%= form_tag state_search_path, :method => "get" do %>
        <%= label_tag(:search, "Add in your 2 letter state code:") %><br>
        <%= text_field_tag :search, params[:search], "size" => 3 %>
        <%= submit_tag("State Search", :name => nil) %>
    <% end %>
</div>

app/views/events/edit.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Event</title>
    <link rel="stylesheet" href="users.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <div>
    <br>
        <h1 class="animate__animated animate__fadeIn">Edit Event</h1>
        <p>Go to <%= link_to "All Events", events_path %></p>

        <%= render 'form' %>
<br>
        <%= form_with model: @event , method: "delete" do %>
            <%= submit_tag "Delete Event", :style => "width: 150px; background-color: #ff0000;" %>
        <% end %>
    </div>
</body>

app/views/events/index.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events</title>
    <link rel="stylesheet" href="users.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <div><br>
        <div>
            <%if @user %>
                <div>
                    <%#= @user.name || @user.username %> 
                    <h1 class="animate__animated animate__fadeIn" style="color:#FFFFFF";>RSVP'd</h1>
                    <h3 class="animate__animated animate__fadeIn" style="color:#FFFFFF";>Upcoming Events</h3><br>
                </div>
                <br>
                <div>
                    <% if @events.empty? %>
                        <p><%= "You haven't signed up for any events yet!" %><p><br>
                        <p style="color: #ffffff;"><%= "We can help you find events in your state." %> <p>
                        <%= render 'statesearch' %>
                    <% end %>
                    <br>
                </div>

            <% else %>

                <div>
                    <br>
                    <% if flash[:message] %>
                    <p style="color:#FF0000";><%= flash[:message] %></p>
                    <% end %>
                </div>

                <div>
                    <h1 class="animate__animated animate__backInUp" style="color:#FFFFFF";>Upcoming Events</h1>
                    <%= link_to "Create New Event", new_event_path %>
                    <%= render 'searchform' %>
                    <br>
                </div>

            <% end %>
        </div>
<br>
        <div>
            <% @events.each do |event| %>
                <% ed = event.date %>
                <%= ed.strftime("%m/%d/%Y") %> -
                <% if @user %>
                    <%= link_to event.title, user_event_path(@user, event) %> -
                <% else %>
                    <%= link_to event.title, event_path(event) %> -
                <% end %>
                
                <%= event.category %>
                <br>
            <% end %>
        </div>

    </div>
</body>
<br></br>
<br></br>

app/views/events/new.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create An Event</title>
    <link rel="stylesheet" href="users.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <div>
    <br>
        <h1 class="animate__animated animate__fadeIn">Create An Event</h1>
        <p>Go to <%= link_to "All Events", events_path %></p>

        <%= render 'form' %>

    </div>
</body>

app/views/events/search.html.erb
<div>
<br>
    <div>
        <h1>Search Results</h1>
    </div>
<br>

    <div>
        <% @events.each do |event| %>
            <%= link_to event.title, event_path(event) %> -
            <% ed = event.date %>
            <%= ed.strftime("%m/%d/%Y") %><br>

        <% end %>
    </div>
    
    <br></br>
    <br></br>

</div>

app/views/events/show.html.erb
<br></br>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @event.title %></title>
    <link rel="stylesheet" href="users.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
</head>

<body>
    <div>

        <h1  class="animate__animated animate__fadeIn" style="color:#FFFFFF";><%= @event.title %></h1>
            Event Focus: <%= @event.category %>
            <br></br>
            <%= @event.date.strftime("%B %e, %Y") %> - 
            <% et = @event.time %>
            <%= et.strftime("%I:%M %p") %>
            <br></br>
            Address: <br>
            <%= @event.address %>
            <br>
            <%= @event.city %> <%= @event.state %>,  <%= @event.zip %>
            <br></br>
            
            Event Summary:
            <li><%= @event.about_content %></li>
            <br>
    </div>
    <div>
        <%= link_to "Edit Event", edit_event_path %>
    </div>
    <br></br>
    <div>
        <% if flash[:notice] %>
        <p style="color:#FF0000";><%= flash[:notice] %></p>
        <% end %>
    </div>
        
    <div>
        <h5 style="color:#FFFFFF";><u>Sign Up For Event with a Comment:</u></h5>
            
            <%= form_for UsersEvent.new, local: true do |f| %>
                <%= f.hidden_field :event_id, value: @event.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.label "Comment" %><br>
                <%= f.text_area :comment %><br>
                <br>
                <%= f.submit("RSVP for event", :style => "width: 150px; background-color: #c49102") %>
            <% end %> 
    </div>
    <br></br>
    <div>

    <h5 style="color:#FFFFFF";><u><%= @event.users_events.count %> RSVP's: </u></h5>
            <% @event.users_events.each do |ue| %>
                <%# byebug %>
            <%= ue.user.name || ue.user.username %> said:
            <%= ue.comment %><br>
                <% if ue.admin == false %> 
                    <% if (ue.user_id == current_user.id)  %>
                        <%= button_to "Delete RSVP", users_event_path(ue), method: :delete, :style => "width: 100px; background-color: #ffffff;" %>
                    <% end %><br>
                <% end %>
            <% end %>
    </div>  

    <br>
    <div>
        <p style="color:#FFFFFF";>Can't make it? Please let us know and delete your RSVP</p>
    </div>
</body>