config/routes.rb
Rails.application.routes.draw do

  # CUSTOM ROUTES ON TOP
  
root 'welcome#home'

get '/login' => "sessions#new"
post '/sessions' => "sessions#create"
get '/logout' => "sessions#destroy"

#get '/auth/:provider/callback' => 'sessions#create'
get '/auth/github/callback' => 'sessions#create'
get '/auth/google/callback' => 'sessions#create'
        # provider is also called 'STRATEGY'

get '/signup' => 'users#new'
        
  resources :users, only: [:new, :create, :show] do
    #nested routes
    resources :events, only: [:index, :show, :new, :create]
    get 'search', to: "events#search"
  end


resources :events
#resources :categories, except: [:destroy]
# post '/users_events', to: 'users_events#create', as: 'new_usersevent'

resources :users_events, only: [:create, :destroy]
get 'rsvps', to: "users_events#index"

get 'search', to: "events#search"
get 'state-search', to: "events#search_by_state", as: "state_search"

get 'users', to: "users#users"

end

app/views/layouts/_footer.html.erb
<div>
    <% if current_user %>
        <p> You're logged in as: <%= link_to current_user.username, user_path(current_user) %><br>
        <%= link_to "Log Out", logout_path %></p><br> 
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
    <div>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #c49102;">
          <a class="navbar-brand" style="color: white;" href="/">Social Justice Events</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" style="color: #2B4D59;" href="<%= root_path %>">HOME<span class="sr-only">(current)</span></a>
              </li>
              <% if current_user != nil %>
                <li class="nav-item">
                <a class="nav-link" style="color: #2B4D59;" href="<%= user_path(current_user.id) %>">DASHBOARD<span class="sr-only">(current)</span></a>
                </li>
              <% end %>
              <li class="nav-item">
                <a class="nav-link" style="color: #2B4D59;" href="/events">ALL EVENTS</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color: #2B4D59;" href="/events/new">CREATE EVENT</a>
              </li>
              <% if current_user != nil %>
                <li class="nav-item">
                <a class="nav-link" style="color: #2B4D59;" href="<%= logout_path %>">LOG OUT<span class="sr-only">(current)</span></a>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
    <div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
    
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="google-site-verification" content="mHdM6gFNh8j0F0H2Vs3rThjRo9sjU1GLBRfNBFH8ynA" />

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      
    </head>

    <body>
      <center>

      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
      <!--[if lt IE 7]>
        <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
        <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
      <![endif]-->

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        
        <%= render 'layouts/navbar' %>

        <%= yield %>

        <br></br>
        <br></br>

        <footer>
          <%= render 'layouts/footer' %>

          <div>
            <p>©2020 ChangeMakers</p>
            <br></br>
          </div>

        </footer>
        
      </center>
    </body>
      
  </html>